### ISSUE TITLE
When creating offline java buildpack for v4.36, getting error: rake aborted! Invalid version '': missing component

### ISSUE THREAD

**Issue by Krishna1413** [cloudfoundry/java-buildpack#874] opened 2021-05-12 15:13 UTC
bundle exec rake clean package OFFLINE=true PINNED=true
Pinning groovy version to 2.5.9
Pinning spring_boot_cli version to 2.4.2
Pinning tomcat version to 9.0.41
Pinning lifecycle_support version to 3.3.0_RELEASE
Pinning logging_support version to 3.3.0_RELEASE
Pinning access_logging_support version to 3.3.0_RELEASE
Pinning redis_store version to 1.3.6_RELEASE
Pinning geode_store version to 1.13.0
Pinning jre version to 1.8.0_282
Pinning jvmkill_agent version to 1.16.0_RELEASE
Pinning memory_calculator version to 3.13.0_RELEASE
Pinning app_dynamics_agent version to 21.1.0_31582
[VersionResolver]                WARN  Discarding illegal version 2.4.0-BETA: Invalid micro version '0-BETA'
Pinning azure_application_insights_agent version to 2.6.2
Pinning client_certificate_mapper version to 1.11.0_RELEASE
Pinning container_customizer version to 2.6.0_RELEASE
Pinning container_security_provider version to 1.18.0_RELEASE
Pinning contrast_security_agent version to 3.8.0_18457
Pinning dynatrace_appmon_agent version to 7.1.0_1803
Pinning elastic_apm_agent version to 1.20.0
Pinning google_stackdriver_debugger version to 2.26.0
Pinning google_stackdriver_profiler version to 0.1.0
Pinning introscope_agent version to 20.11.0_20
Pinning jacoco_agent version to 0.8.6
Pinning agent version to 0.5.0
Pinning clean_up version to 0.1.0
Pinning jprofiler_profiler version to 11.1.4
Pinning jrebel_agent version to 2021.1.0
Pinning luna_security_provider version to 7.4.0
Pinning maria_db_jdbc version to 2.7.1
Pinning metric_writer version to 3.4.0_RELEASE
Pinning new_relic_agent version to 6.3.0
Pinning postgresql_jdbc version to 42.2.18
Pinning protect_app_security_provider version to 8.4.0
rake aborted!
Invalid version '': missing component
/java-buildpack/lib/java_buildpack/util/tokenized_version.rb:155:in `validate'
/java-buildpack/rakelib/dependency_cache_task.rb:218:in `new'
/java-buildpack/lib/java_buildpack/util/tokenized_version.rb:43:in `initialize'
/java-buildpack/rakelib/dependency_cache_task.rb:218:in `version'
/java-buildpack/rakelib/dependency_cache_task.rb:185:in `block in get_from_cache'
/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `block in cached'
/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `cached'
/java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:81:in `get'
/java-buildpack/rakelib/dependency_cache_task.rb:183:in `get_from_cache'
/java-buildpack/rakelib/dependency_cache_task.rb:175:in `block (2 levels) in uris'
/java-buildpack/rakelib/dependency_cache_task.rb:173:in `each'
/java-buildpack/rakelib/dependency_cache_task.rb:173:in `block in uris'
/java-buildpack/rakelib/dependency_cache_task.rb:172:in `each'
/java-buildpack/rakelib/dependency_cache_task.rb:172:in `uris'
/java-buildpack/rakelib/dependency_cache_task.rb:46:in `initialize'
/java-buildpack/Rakefile:42:in `new'
/java-buildpack/Rakefile:42:in `<top (required)>'
/java-buildpack/vendor/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/java-buildpack/vendor/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
/java-buildpack/vendor/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'

**Comment by Krishna1413** [comment] 2021-05-13 11:14
Unable to create offline buildpack, getting below error:
Pinning riverbed_appinternals_agent version to
rake aborted!
Unable to resolve version '11.7.1_BL521' for platform ''

Please suggest.

**Comment by dmikusa-pivotal** [comment] 2021-05-13 13:28
Did you `git checkout v4.36` prior to trying to package? Post the output of `git status`. Also, can you run `bundle exec rake versions` & post the output?

**Comment by vorbidan** [comment] 2021-05-17 20:25
I am facing the same issue for v4.28, v4.34, v4.36
```
❯ git status
HEAD detached at v4.36
nothing to commit, working tree clean
```
❯ bundle exec rake versions
[VersionResolver]                WARN  Discarding illegal version 2.4.0-BETA: Invalid micro version '0-BETA'
rake aborted!
Unable to resolve version '11.7.1_BL521' for platform ''
/private/tmp/java-buildpack/rakelib/versions_task.rb:193:in `block in get_from_cache'
/private/tmp/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `block in cached'
/private/tmp/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/private/tmp/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/private/tmp/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `cached'
/private/tmp/java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:81:in `get'
/private/tmp/java-buildpack/rakelib/versions_task.rb:188:in `get_from_cache'
/private/tmp/java-buildpack/rakelib/versions_task.rb:211:in `block (2 levels) in dependency_versions'
/private/tmp/java-buildpack/rakelib/versions_task.rb:210:in `each'
/private/tmp/java-buildpack/rakelib/versions_task.rb:210:in `block in dependency_versions'
/private/tmp/java-buildpack/rakelib/versions_task.rb:207:in `each'
/private/tmp/java-buildpack/rakelib/versions_task.rb:207:in `dependency_versions'
/private/tmp/java-buildpack/rakelib/versions_task.rb:292:in `versions'
/private/tmp/java-buildpack/rakelib/versions_task.rb:251:in `block in version_task'
/Users/vorbid6611e/.rbenv/versions/2.5.8/bin/bundle:23:in `load'
/Users/vorbid6611e/.rbenv/versions/2.5.8/bin/bundle:23:in `<main>'
Tasks: TOP => versions
(See full trace by running task with --trace)
```

**Comment by vorbidan** [comment] 2021-05-17 23:21
@dmikusa-pivotal after updating the version in `config/riverbed_appinternals_agent.yml` to the lates from the repo (11.8.1_BL526) all builds are succeeding, including very old ones (tried against v4.36, v4.28, v4.29).

This leads me to believe that there is a bug in retrieving cached versions of riverbed agent

**Comment by vorbidan** [comment] 2021-05-17 23:35
looks like problem with the repository. It returns a single version:
```
>curl https://pcf-instrumentation-download.steelcentral.net/index.yml
11.8.1_BL526: https://pcf-instrumentation-download.steelcentral.net/riverbed-appinternals-agent-11.8.1_BL526.zip
```

**Comment by dmikusa-pivotal** [comment] 2021-05-18 13:04
OK, so your config file has `version: 11.7.1_BL521`, but it should have `version: 11.+`. The `11.+` says to use basically any version with the major version of 11. This is more permissive so it'll always grab the latest.

I suspect that perhaps you pinned the version on a previous packaging run, as pinning the version will update your config files with the current set of latest versions at the time it runs. So if I do a build today, it would pin and update the version to `11.8.1_BL526`. If I come back and build 6 months from now, that version may no longer exist which would cause the problem you observed.

After you do a build and pin versions, it's a good idea to `git checkout` and reset any files modified during the package process (I think it's just files under `config/`). That'll give you a clean slate for the next packaging run.

Hope that helps! Is it OK if I close this out?

**Comment by vorbidan** [comment] 2021-05-18 13:58
Thank you for replying.
Having a wildcard version would make sense if we were building from the main branch, but we are building from a tag, and as such the version is already pinned by you release process. 
We also are building from a fresh checkout, so there are no traces of previous build runs.
The way it stands right now only v4.37 and v4.38 can be built, because they reference the same riverbed library version - the latest.
I believe the problem is with the `index.yml` for riverbed agent repo listing a single version - the latest one. Other repos, for example, app dynamics, are listing multiple previous versions.

Hope this makes sense.

**Comment by vorbidan** [comment] 2021-05-18 14:31
take a look at 
```
curl https://pcf-instrumentation-download.steelcentral.net/index.yml
```
vs.
```
curl https://packages.appdynamics.com/java/index.yml
```

**Comment by vorbidan** [comment] 2021-05-18 14:49
@dmikusa-pivotal 
I did additional testing with deploying a java app with a buildpack pointing to v4.34 and making sure that the riverbed agent will also be pulled, and it failed staging the app:
```
cf push vcap-demo -p ./build/libs/vcapdemo-0.0.1-SNAPSHOT.jar -b https://github.com/cloudfoundry/java-buildpack.git#v4.34 -k 1gb -m 1gb

cf cups vcap-demo-appinternals -p '{"rvbd_dsa_port":"9999","rvbd_moniker":"vcap-demo"}'

cf bind-service vcap-demo vcap-demo-appinternals 

cf restage vcap-demo  
...
2021-05-18T08:43:38.50-0600 [STG/0] ERR [Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: Riverbed Appinternals Agent error: No version resolvable for '10.21.5_BL512' in 11.8.1_BL526>
   2021-05-18T08:43:38.51-0600 [STG/0] ERR Failed to compile droplet: Failed to run finalize script: exit status 1
   2021-05-18T08:43:38.56-0600 [STG/0] OUT Exit status 223
...
```

**Comment by dmikusa-pivotal** [comment] 2021-05-18 15:07
>Having a wildcard version would make sense if we were building from the main branch, but we are building from a tag, and as such the version is already pinned by your release process.

You're right, sorry. I overlooked that.

>I believe the problem is with the index.yml for riverbed agent repo listing a single version - the latest one. Other repos, for example, app dynamics, are listing multiple previous versions.

Yes, I see what you're saying. The index.yml is changing and removing the old versions. I can ask about this, but it's controlled by the partner, so I cannot update it myself.

In the short term, you could make your own index.yml file. It seems like the actual files are still being hosted by the partner. It's just the index.yml that's removing the old entries.

```
# download latest version
dmikusa@dmikusa-a01 ~/D/artifactory-resource (main)> curl -L -O https://pcf-instrumentation-download.steelcentral.net/riverbed-appinternals-agent-11.8.1_BL526.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.1M  100 17.1M    0     0  6233k      0  0:00:02  0:00:02 --:--:-- 6230k

# download older version
dmikusa@dmikusa-a01 ~/D/artifactory-resource (main)> curl -L -O https://pcf-instrumentation-download.steelcentral.net/riverbed-appinternals-agent-10.21.5_BL512.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.4M  100 17.4M    0     0  6948k      0  0:00:02  0:00:02 --:--:-- 6945k
```

**Comment by vorbidan** [comment] 2021-05-18 18:08
I think we will go with a `version: +` in the corresponding yaml config file. This gives us better flexibility during the build time, especially in the case of the offline buildpack.
But I think that the permanent solution would be to get in touch with the vendor, who maintains the index.yml and let them know that it breaks deployments with a reference to tagged java buildpacks older than v4.37

Thank you,

--Vitaliy

**Comment by dmikusa-pivotal** [comment] 2021-05-18 18:23
I reached out to the vendor. I'll see what I can do about getting more versions listed in the index.yml. Thanks for your patience on this.

**Comment by dmikusa-pivotal** [comment] 2021-05-21 19:06
I got word back from the vendor today and they have added the entries back into the index.yml. I did a quick curl test and was able to see them. Please check again and see if it is working for you all. Let me know if you still see issues. Thanks!

**Comment by vorbidan** [comment] 2021-05-21 22:08
It looks good now. Thank you for fixing this.

**Closed** 2021-06-24 13:29 UTC
