### ISSUE TITLE
Add AWS Xray Tracing Support to Build pack

### ISSUE THREAD

**Issue by ygrene-austin** [cloudfoundry/java-buildpack#448] opened 2017-06-16 22:04 UTC
We love cloud foundry, pcf and all things 12 factor. We have recently started using AWS X-Ray in our JVM based services. We would love to see this supported in the java build pack.
Currently these services are on elastic beanstalk and here is how we install them.
```
commands:
  700-download-daemon:
    command: curl https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-2.x.rpm -o /home/ec2-user/xray.rpm
    cwd: /tmp
  701-install-daemon:
    command: yum install -y /home/ec2-user/xray.rpm
    cwd: /tmp
    ignoreErrors: true
  702-check-daemon-installed:
    command: yum list installed xray
```

**Comment by nebhale** [comment] 2017-06-19 16:33
I've been looking this over and it doesn't look great as it appears that it needs system-level software (rather than a Java Agent) which means that we can't integrate it with the buildpack.  I'll keep investigating and come up with definitive answer in the next couple of days.

**Comment by nebhale** [comment] 2017-06-19 19:12
Yeah, I've confirmed this with out Spring Sleuth team as well as my own analysis.  At the moment, X-Ray is *super* tied to OS-level daemons which just aren't a good fit for inside the container that Cloud Foundry applications are run in.  Contrast that with Google and Azure's support for OpenZipkin services and their pure-Java agents that run in process.  Because of this, we won't be adding support to the buildpack for Amazon X-Ray.

If you think that I've gotten this analysis wrong or have a different idea of how we might integrate it, I'm happy to hear it.

**Comment by nebhale** [comment] 2017-07-17 16:12
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Closed by nebhale** 2017-07-17 16:12 UTC
