### ISSUE TITLE
OutOfMemory: Metaspace error

### ISSUE THREAD

**Issue by cskinfill** [cloudfoundry/java-buildpack#391] opened 2017-03-06 01:03 UTC
I've noticed a number of `OutOfMemory: Metaspace` errors over the last few days with an app running in an internal cloudfoundry service.  Could this be related to the v3 memory calculator?  I also realized we're just naively grabbing the latest buildpack, so i'm going to explicitly load v3.4 and see if that changes anything.

**Comment by LeeU1911** [comment] 2017-03-06 05:19
I second this. When I changed to use an internally modified version of the buildpack v3.10, the OOM error goes away. Probably something with the memory calculator. Even when I tried to increase memory size, it didn't help.

**Comment by mjj1409** [comment] 2017-03-06 14:14
I'm having the same issue, I reverted to v3.13 and this stopped the memory errors for now

> -b https://github.com/cloudfoundry/java-buildpack.git#v3.13

**Comment by glyn** [comment] 2017-03-06 15:11
We are in the process of making the memory calculator allocate more metaspace and compressed class space. See [commit c9867a6](https://github.com/cloudfoundry/java-buildpack-memory-calculator/commit/c9867a693b5f7fafb5bc1eec2ad310e4548bf314) for details.

**Comment by glyn** [comment] 2017-03-06 16:00
Memory calculator v3.2.0.RELEASE is available. Please retry your application pushes and see if they now work.

**Comment by markbigler** [comment] 2017-03-06 16:05
I think this is a duplicate of https://github.com/cloudfoundry/java-buildpack/issues/390

**Comment by glyn** [comment] 2017-03-06 17:26
@markbigler I don't mind dual-maintaining this and #390 because this one is metaspace-specific and the other is a bit more general. Hopefully the fixes will be common though.

**Comment by glyn** [comment] 2017-03-07 08:20
@cskinfill Closing. Please re-open if the problem is still occurring.

**Closed by glyn** 2017-03-07 08:20 UTC
