### ISSUE TITLE
make OnOutOfMemoryError handling configurable in java-buildpack since killing the process can cause problems for applications that don't have memory leaks

### ISSUE THREAD

**Issue by lhotari** [cloudfoundry/java-buildpack#156] opened 2015-03-05 21:36 UTC
The current solution in java-buildpack kills the running JVM when an OutOfMemoryError happens. This causes problems to some applications that run fine most of the time and don't contain actual memory leaks. The OOMEs are caused by some parts of the application consuming too much memory to produce a report etc. .

I have created [a simple servlet that demonstrates this type of situation](https://github.com/lhotari/hello-jbp-diagnostics/blob/master/src/main/groovy/io/github/lhotari/hello/AllocMemServlet.groovy). You can run it locally with `./gradlew tomcatRun` and access the url http://localhost:8080/hello-jbp-diagnostics/allocmem . 

Without the OnOutOfMemoryError script, the JVM would recover just fine since after the OutOfMemoryError, the thread would exit it's current processing loop and any memory allocated during that processing would be free for GC. That can be demonstrated with the AllocMemServlet sample.

I assume that The OnOutOfMemoryError script would have to do it's work asynchronously and wait a short time period (1-2 seconds) to see if the app recovers after the thread(s) that received the OutOfMemoryError have exited their processing loops and released the allocated memory for GC.

**Comment by lhotari** [comment] 2015-03-05 21:55
It would be possible to add custom OutOfMemoryError handling that happens inside the JVM with [Thread.setDefaultUncaughtExceptionHandler](http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setDefaultUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler)) . That logic could take care of tracking whether the OOM is "real" by keeping track of the rate of OOMEs. I'm not sure if it's possible to use the OnOutOfMemoryError JVM option together with the UncaughtExceptionHandler. Just some implementation ideas for the improved "memory leak" detection that seems to be the original reason to add the killjava.sh solution.

**Comment by cgfrost** [comment] 2015-05-29 14:09
Do you have a genuine use case where an application throws an OOM legitimately. This really shouldn't happen and I'm inclined to say the problem is in the application or it just needs to be assigned more memory.

**Comment by lhotari** [comment] 2015-05-29 14:55
@cgfrost In most cases a Java application and the JVM is able to recover from an OOME that is caused by a thread allocating too much memory in the current execution stack. The JVM usually recovers from this type of situation when the OOME happens since the memory allocated from objects in the execution stack will get released after the OOME.

Please look at the example servlet that demonstrates this type of situation: https://github.com/lhotari/hello-jbp-diagnostics/blob/master/src/main/groovy/io/github/lhotari/hello/AllocMemServlet.groovy . The JVM recovers after the OOME happens.

I once worked with a legacy system where requesting a certain report with too broad filters caused the processing to fail in an OOME. The JVM recovered just fine from that situation after the OOME. Users just learned that they should not request too much data in the report and use filters to limit the amount of data. Not perfect, but the users were able to live with this "feature".
 
I think that the behaviour of OOME handling should be configurable in the Java build pack because in some cases the JVM might be able to recover from the OOME. An OOME isn't the end of the world in all cases.

**Comment by youngm** [comment] 2015-05-29 15:09
@cgfrost @lhotari another reason to put some OOM handling in a DefaultUncaughtExceptionHandler is the case of container thread exhaustion.  https://github.com/cloudfoundry/java-buildpack/issues/161

In this case the OOM handler on the commandline doesn't work because there isn't a thread to execute the kill process.

This may be just another reason to put some OOM handling in a DefaultUncaughtExceptionHandler.

**Comment by cgfrost** [comment] 2015-05-29 15:09
OK. I did look at the example servlet and I understand what your explaining but I can't think of a situation where it's correct for an OOME to get thrown. As you say, the situation you have explained isn't perfect but users could live with it. We will discuss this further here as there may be a better solution, e.g. around making the max thread count configurable, I don't know. I will respond back here again.

**Comment by cgfrost** [comment] 2015-05-29 15:14
@youngm I have spotted the overlap between these two issues. Will take it in to account.

**Comment by rafaelri** [comment] 2015-10-17 18:14
@lhotari I can see another scenario that the JVM might throw an OOME and still recover just fine. Still using the report scenario you described, we could have this triggered even without a single user requesting too much data. Imagine we have an application with 500MB of usable heap. If we have (theoretically) 10 concurrent requests that demand 50MB each the application would probably respond without any OOME. But if for any reason we have more than this we risk that threads trigger an OOME and still part of them would be able to respond and more importantly, later on the application will be still working fine as the memory would be reclaimed (probably on a single GC since the data would probably be still on eden).
@cgfrost I agree with you that there is an overlap between them and I'd like to add that we should probably let the user pick between a default killing behavior (we should make it easy for the regular user) and let them disable. I'd also like to point that the agent suggested by @youngm on cloudfoundry/java-buildpack#161 is probably a nice place to implement something similar to what @lhotari suggested of having a kill threshold. I have a suggestion, we could pass 2 parameters the agent: the ammount of ResourceExhausted events and a time frame. And everytime our agent got a  ResourceExhausted event we would check if we were still on the same interval (something like System.currentTimeMillis/interval) and: 1) if still on the same interval, increment counter and check if threshold was reached; 2) if we were on another interval we would reset the counter to 1. This way we could let the user configure a threshold for killing the vm without resorting to some kind of timer or thread on the agent. Sorry for such a long post.

**Comment by rafaelri** [comment] 2015-10-17 18:19
@cgfrost what is the default way for providing those configuration points in the buildpack? Environment variables?

**Comment by rafaelri** [comment] 2015-10-19 01:49
I took the time to do a quick and dirty attempt of implementing this on top of the original https://github.com/airlift/jvmkill agent and it is available at https://github.com/rafaelri/jvmkill/blob/counter/jvmkill.c (although it still needs some improving in the code as I am no C expert and also still lacks the possibility of passing parameters to the agent).

**Comment by cgfrost** [comment] 2015-10-19 13:37
@rafaelri Environment variables is correct. Also, since this issue was first raised the available memory settings of the buildpack have become much better. e.g. https://github.com/cloudfoundry/java-buildpack/blob/master/config/open_jdk_jre.yml

**Comment by nebhale** [comment] 2017-03-08 23:01
Resolved with 8ecba51048191989b7fa7c2bf01e4f03a539f30b

**Closed by nebhale** 2017-03-08 23:01 UTC

**Comment by iKrushYou** [comment] 2018-10-17 03:13
Hi all, I'm running into this (if not a similar) issue. I've got a scheduled job that uses up a lot of memory and then clears it after the run. It runs fine and without failure (for at least much more iterations) on my local machine, but when run on PCF (1GB / 2GB / 4GB memory settings) it will crash after the 16th iteration. No matter what I set the memory at. I've looked at it on a profiler and it seems like eventually the memory usage levels out and becomes maintainable but for some reason PCF doesn't like it. I'm getting a `[ERR] jvmkill killing current process`
