### ISSUE TITLE
JaCoCo Support?

### ISSUE THREAD

**Issue by jonathanamartin** [cloudfoundry/java-buildpack#529] opened 2017-12-11 20:14 UTC
Is [JaCoCo](http://www.jacoco.org/jacoco) support on the roadmap for the Java Buildpack?

**Comment by nebhale** [comment] 2017-12-11 21:47
It is not.  The buildpack is responsible for setting up the execution environment for an application, generally in production or QA workloads.  Integrating JaCoCo, a development tool, into the buildpack doesn't seem to be a good fit with that goal.

What use case are you trying to solve by integrating it into the buildpack instead of into your application's build?

**Comment by jonathanamartin** [comment] 2017-12-12 18:31
We use JaCoCo for test coverage metrics for unit tests at build time.  We also do integration tests on deployed apps.  JaCoCo provides test coverage for the integration tests performed against the running app. 

To do this, we're currently embedding the [JaCoco Agent](http://www.jacoco.org/jacoco/trunk/doc/agent.html) in the app then referencing it via `JAVA_OPTS`.

e.g
```
-javaagent:[yourpath/]jacocoagent.jar=[option1]=[value1],[option2]=[value2]
```
Would it make sense to manage the JaCoCo agent as a framework in the buildpack?  Or would this be something we should manage ourselves say in the `resources` directory?

**Comment by nebhale** [comment] 2017-12-12 18:43
How do you get data out of the agent and back to a system to visualize it?

**Comment by jonathanamartin** [comment] 2017-12-12 19:37
You can set a port to expose data from or set an IP address and the data
will be piped to the address by the agent.  On Cloud Foundry we're using
the latter.

**Comment by nebhale** [comment] 2017-12-12 19:45
Then this is a reasonable choice for a framework integration.  We'd expose that metadata via a service binding (probably a user-provided service in most cases).  Why don't you start by putting some more information in this issue with regards to documentation about where the agent lives, what kind of configuration you currently do, documentation about how the agent is configured, etc.  Let's use this issue to flesh out what the integration will look like and then we'll get on it.

**Comment by jonathanamartin** [comment] 2017-12-13 19:20
Sounds good.  As mentioned, we're embedding the agent JAR in the app.  Here's an example of the options we're using:

```
JAVA_OPTS: -javaagent:/home/vcap/app/WEB-INF/org.jacoco.agent-0.7.10-runtime.jar=output=tcpclient,address={address},port={port}
```
However, it may make sense to provide support for [other options](http://www.jacoco.org/jacoco/trunk/doc/agent.html).

Not sure if this is needed but v 0.7.10 is important for us because it ["reduce[s] chance of conflict with other agents"](https://github.com/jacoco/jacoco/pull/555)

**Comment by nebhale** [comment] 2017-12-13 20:07
Looking over the list, `output`, `address`, and `port` are obvious choices as you've used them.  Any thought on if people commonly used `includes` and `excludes`?  Also, would it be useful to tie `sessionid` to something like the instance identifier created by the platform?  Finally, since we do allow a user to start JMX access tunneled over an SSH connection into the container, would enabling JMX access be appropriate?

**Comment by jonathanamartin** [comment] 2017-12-14 21:35
Sorry for the delay.  We haven't used `includes` or `excludes` but I could see use cases where they would apply.  Agreed, instance ID as the `sessionid` makes sense.

**Comment by nebhale** [comment] 2017-12-14 22:04
Great, that should be enough for me to get started.

On another note, there [doesn't appear to be a v0.7.10](http://www.jacoco.org/jacoco/).

**Comment by jonathanamartin** [comment] 2017-12-14 22:07
You're correct.  Looks to be a snapshot still.
http://www.jacoco.org/jacoco/trunk/doc/changes.html

**Comment by nebhale** [comment] 2017-12-14 23:50
@jonathanamartin You should be able to test this now.  You can push an application with a bound service [as documented](https://github.com/cloudfoundry/java-buildpack/blob/dc8284af626a6a356d6974a7ad120dbb231fd932/docs/framework-jacoco_agent.md) and a buildpack specified by `-b https://github.com/cloudfoundry/java-buildpack.git#529-jacoco`.  You should see the agent downloaded during staging and data should stream to it at runtime.

**Comment by jonathanamartin** [comment] 2017-12-15 15:54
Thanks @nebhale.  I'm in an environment that has fairly stringent network policies so I'll have to see what I can do to test.   I'll keep you posted.

**Comment by jonathanamartin** [comment] 2017-12-15 20:33
@nebhale I've been discussing the usage of JaCoCo as a means to analyze integration test coverage at runtime with a few colleagues where I work.  There has been discussion about dev/prod parity and that we would never want JaCoCo to be used in production. 

That said, we could blacklist its usage through our CI/CD pipelines.  However, given that we would never use it in production do you still think it's a good candidate for a `framework` in the buildpack?

**Comment by nebhale** [comment] 2017-12-15 20:54
You seemed to think so earlier, so there's at least someone who thinks its a good candidate. 😄 We have precedent for things you'd never want to run in production like [Debug](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-debug.md), [JRebel](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-jrebel_agent.md), [JMX](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-jmx.md), and [Profiling](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-your_kit_profiler.md), so adding dev integrations isn't something we shy away from.

I've got some opinions about whether to integrate it, but not strongly held ones.  For something like this, we'd never add it proactively, but someone asked, it doesn't harm other users, and so I've implemented it.  If you are having second thoughts, there's no problem *not* adding it at this point.

**Comment by bhanafee** [comment] 2017-12-19 03:36
Since there are other dev integrations, adding JaCoCo support makes sense. It is widely used, and there do exist system and integration test cases where it would be useful to gather coverage data.

**Comment by jonathanamartin** [comment] 2017-12-19 14:24
@nebhale and @bhanafee thanks for the feedback.  @nebhale let's proceed.  I'll do the validation you had requested.  Thanks for the outstanding support!

**Comment by nebhale** [comment] 2017-12-19 14:30
Great.  I look forward to confirmation.

**Comment by tdrury** [comment] 2017-12-19 17:06
is it possible to reference this jacoco-enabled buildpack in an MTA yaml?

**Comment by nebhale** [comment] 2017-12-19 19:51
I’m not an expert in SAP’s CF distribution, but since it is a certified distribution it’s supposed to be able to run all official buildpacks.  As this is a branch of the official Java Buildpack, I’d expect it to work.  Give it a try and let me know 😄

**Comment by tdrury** [comment] 2017-12-19 20:08
I want to try, but I'm unsure of the syntax of the mtad.yaml file to use a buildpack from a URL instead of:
  type: java.tomcat

**Comment by tdrury** [comment] 2017-12-19 21:45
is specifying the buildpack the only thing I need? I managed to deploy an MTA with the buildpack URL of the 529-jacoco branch, but I don't see "jacoco" in the VCAP_SERVICES of the Java app.

**Comment by nebhale** [comment] 2017-12-19 23:09
Buildpack syntax can [take the form of a URI](https://docs.cloudfoundry.org/buildpacks/custom.html#deploying-with-custom-buildpacks).  So you can specify `-b http://github.com/cloudfoundry/java-buildpack.git#529-jacoco` or the manifest equivalent of the same.

**Comment by michele-mancioppi** [comment] 2017-12-20 06:00
@tdury, MTA is an SAP thing. I doubt @nebhale and the rest of the community can help you with that. Please use thebinternal cf-users mailing list ;-)

**Comment by tdrury** [comment] 2017-12-20 11:55
I believe I have it specified correctly. When deploying I'm getting this in the logs:
2017-12-19T16:36:28.47-0500 [STG/0] OUT -----> Java Buildpack cb0d48e | https://github.com/cloudfoundry/java-buildpack.git#cb0d48e

which is the correct git hash for 529-jacoco. But I'm not seeing jacoco in VCAP_SERVICES.

**Comment by nebhale** [comment] 2017-12-20 14:29
It’s up to you to create the service binding in order to communicate the credential information (in this case, primarily the endpoint) to the buildpack and the running application.  [As documented](https://github.com/cloudfoundry/java-buildpack/blob/529-jacoco/docs/framework-jacoco_agent.md#user-provided-service-optional) the most likely way for you to do this today is by creating a [user provided service](https://docs.cloudfoundry.org/devguide/services/user-provided.html) with this payload.  If this becomes a very common use case for you, you might one day create a service broker for it.

**Comment by jonathanamartin** [comment] 2017-12-27 17:55
@nebhale I see a "downloading" message in the logs:
```
Downloading [1m[34mJacoco Agent[0m[22m [34m0.7.9[0m from https://java-buildpack.cloudfoundry.org/jacoco/jacoco-0.7.9.jar [3m[32m(0.2s)[0m[23m
```
However, the app crashed and I received the following error:
```
2017-12-27T12:46:26.974-05:00 [API/25] [OUT] Process has crashed with type: "web"
2017-12-27T12:46:26.982-05:00 [API/25] [OUT] App instance exited with guid 4610a393-6ad9-44f6-b74d-9754b078c7fd payload: {"instance"=>"29808c3d-f8a1-4c7a-6464-5cf0", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>2, "crash_timestamp"=>1514396786944906655, "version"=>"a2505af2-ef05-4ff3-904d-26a8f5fc2ed0"}
2017-12-27T12:46:27.117-05:00 [CELL/0] [OUT] Creating container
2017-12-27T12:46:27.433-05:00 [CELL/0] [OUT] Successfully destroyed container
2017-12-27T12:46:27.680-05:00 [CELL/0] [OUT] Successfully created container
2017-12-27T12:46:32.037-05:00 [CELL/0] [OUT] Starting health monitoring of container
2017-12-27T12:46:32.163-05:00 [APP/PROC/WEB/0] [OUT] JVM Memory Configuration: -Xmx430625K -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105950K -XX:ReservedCodeCacheSize=240M -Xss1M
2017-12-27T12:46:32.174-05:00 [APP/PROC/WEB/0] [OUT] Error occurred during initialization of VM
2017-12-27T12:46:32.174-05:00 [APP/PROC/WEB/0] [OUT] agent library failed to init: instrument
2017-12-27T12:46:32.174-05:00 [APP/PROC/WEB/0] [ERR] Failed to find Premain-Class manifest attribute in /home/vcap/app/.java-buildpack/jacoco_agent/jacoco_agent-0.7.9.jar
2017-12-27T12:46:32.195-05:00 [APP/PROC/WEB/0] [OUT] Exit status 1
```
Found [this](https://groups.google.com/forum/#!topic/jacoco/heRn1Hhvq14), though not much info.

I'll do some more digging.  It could be that I used an invalid/mock `address` (127.0.0.1) because I had to test on PWS.

**Comment by iyergn** [comment] 2018-01-03 19:11
@jonathanamartin : Just to clarify in our non-PCF implementation (e.g. with puppet) we have implemented it such that we only have the Jacoco integration switched ON for the deployments to the test environments excluding Performance Testing environment.
In other words the Jacoco integration will be not be in play for Performance testing, Staging and Production environments. We manage this through a "switch" which manages the way the application is deployed to those nodes.
Hope this clarifies that aspect better. I saw some comments about not turning this in production and we are more than aware about it and also account for that in our current practices as well and plan to do the same with PCF.

**Comment by nebhale** [comment] 2018-01-03 20:15
@jonathanamartin Yeah, the problem is that it's the "wrong" JAR.  Apparently Mountainminds distributes a wrapper archive as a JAR (are they the only people to do this any more?) and that JAR contains _another_ JAR which is what should be the agent.  I'll make some changes and let you know when you're ready for testing.

**Comment by jonathanamartin** [comment] 2018-01-03 20:56
@nebhale, good question.  Not sure how widely used this is.  Would usage
affect its candidacy as a framework?

Regarding the JAR, is [this](
http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.jacoco) where you got it
from?

**Comment by nebhale** [comment] 2018-01-03 22:22
Yes I get it from Maven Central, and no, there's no problem with it, I just need to account for it.

**Comment by jonathanamartin** [comment] 2018-01-06 17:00
Understood.  Thank you sir.

**Comment by nebhale** [comment] 2018-01-17 18:37
Thanks for you patience on this.  I've just finished the update so you can test against the same branch now.

**Comment by jonathanamartin** [comment] 2018-01-17 19:20
Thanks will do.

**Comment by jonathanamartin** [comment] 2018-01-18 15:04
@nebhale I'm getting: 
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.IllegalArgumentException: Unknown agent option "session_id"
...
FATAL ERROR in native method: processing of -javaagent failed
```
Should it be `sessionid`?

**Comment by nebhale** [comment] 2018-01-18 15:30
Yep, it should be; the risk in trying to write code you can’t test directly.  I’ll make an update as soon as I get into the office.

**Comment by nebhale** [comment] 2018-01-18 16:58
OK @jonathanamartin, have another go.

**Comment by jonathanamartin** [comment] 2018-01-18 19:13
Looks like the agent is staged now:

```
-[1m-[31m----->-[0m-[22m Downloading -[1m-[34mJacoco Agent-[0m-[22m -[34m0.8.0-[0m from https://java-buildpack.cloudfoundry.org/jacoco/jacoco-0.8.0.jar -[3m-[32m(0.1s)-[0m-[23m
2018-01-18T13:57:25.760-05:00 [STG/0] [OUT] Expanding Jacoco Agent to .java-buildpack/jacoco_agent -[3m-[32m(0.0s)-[0m-[23m
```
I had to use a dummy `address` and `port` because I'm using PWS and can't point back to my corporate client. :)  

Let me see what I can do to test the options.

**Comment by ishaan2007** [comment] 2018-01-25 21:17
we will be able to override /specify sessionid correct?

**Comment by xunwu** [comment] 2018-01-26 23:09
Hi All,
I have pushed an app to the cloud foundry with this "-b http://github.com/cloudfoundry/java-buildpack.git#529-jacoco" option and I can see my app successfully started, but I cannot see any logs related to jacoco, I am wondering is there any other configuration I need to do for the jacoco to generate the coverage report, for example specify JAVA_OPTS related to jacoco?

**Comment by nebhale** [comment] 2018-01-29 17:27
@xunwu Please see the [documentation](https://github.com/cloudfoundry/java-buildpack/blob/dc8284af626a6a356d6974a7ad120dbb231fd932/docs/framework-jacoco_agent.md)

**Comment by xunwu** [comment] 2018-01-29 18:00
@nebhale So do you mean that I should create a jacoco service and bind it to my application?
So I cannot find any jacoco service in marketplace, how can I create one?

**Comment by shinmyung0** [comment] 2018-01-29 18:07
@xunwu I think you should be creating a User-Provided service with the appropriate credentials

**Comment by nebhale** [comment] 2018-01-29 18:12
The documentation describes the payload for a user-provided service.  You should use one of those.

**Comment by xunwu** [comment] 2018-01-29 18:33
@nebhale Sorry I am new to user-provided service, but do I need to create a user-provided service by using "  cf cups '{"address":"127.0.0.1","includes":"*", "port":"1010"}' " but what address and port should I use, is it the address for some jacoco microservice running on the cloud foundry?

**Comment by xunwu** [comment] 2018-01-29 18:47
I used this option and see Jacoco being downloaded
 -----> Downloading Jacoco Agent 0.8.0 from https://java-buildpack.cloudfoundry.org/jacoco/jacoco-0.8.0.jar (1.0s)
          Expanding Jacoco Agent to .java-buildpack/jacoco_agent (0.0s)

name:              xun-javaexample
requested state:   started
instances:         1/1
usage:             928M x 1 instances
routes:            xun-javaexample-introspective-ovolo.run.aws-usw02-pr.ice.predix.io
last uploaded:     Mon 29 Jan 09:55:49 PST 2018
stack:             cflinuxfs2
buildpack:         http://github.com/cloudfoundry/java-buildpack.git#529-jacoco
start command:     JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.12.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR
                   -javaagent:$PWD/.java-buildpack/jacoco_agent/jacocoagent.jar=address=127.0.0.1,output=tcpclient,sessionid=$CF_INSTANCE_ID,includes=*,port=1010
                   -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security
                   $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.10.0_RELEASE -totMemory=$MEMORY_LIMIT -stackThreads=250 -loadedClasses=13289
                   -poolType=metaspace -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && SERVER_PORT=$PORT JAVA_OPTS=$JAVA_OPTS
                   JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre exec $PWD/java-hello-world-cf-example/bin/java-hello-world-cf-example


So how can I grab the jacoco data on the fly?

**Comment by shinmyung0** [comment] 2018-01-29 18:53
@nebhale  This was one thing I was also wondering, can it be something like a go-route with port 80 or 443? Or does it need to be a tcp route?

**Comment by xunwu** [comment] 2018-01-29 21:36
@shinmyung0 if you look at here http://www.eclemma.org/jacoco/trunk/doc/agent.html
the jacoco report can only dump through TCP Connection, I am also wondering how do you trigger jacoco to generate the report

**Comment by xunwu** [comment] 2018-02-06 00:53
I was trying this Jacoco build pack for a while but even though I got this configuration set up in cloud foundry, and see that it has the same JAVA_OPTS as in my local, I am not able to dump the file, I set up the jacoco to dump through tcp connection and use localhost and CF_INSTANCE_PORT to dump the report on the same instance, but it got an error for java.io.IOException: Invalid execution data file.so that means cloud foundry is not allowing jacoco agent to export data? I looked at the source code, which means the output stream is not in correct format or it could be an empty output stream, I am little confused, so cloud foundry is not allowing any other process to use any port in that container?

**Comment by nebhale** [comment] 2018-02-12 20:42
@jonathanamartin Did you ever get a chance to test this?

**Comment by jonathanamartin** [comment] 2018-02-13 14:23
@nebhale I apologize, facing a few roadbloack on my end and haven't been able to take the testing any further.  Though, I have something in mind and will get back with you in a day or so.  Thank you for your patience.

**Comment by nebhale** [comment] 2018-02-13 23:37
No need to apologize.  I'm buttoning down `v4.9` now and want to get it in if possible.  If not, it'll just slide out to `v4.10`.

**Comment by Aeolic** [comment] 2018-02-14 15:04
Hi @nebhale, I'm currently using the jacoco Buildpack and it works great - the only problem right now (really minor) is that I don't get any Session IDs, the applications are started with "sessionid=$CF_INSTANCE_ID" as intended, but the session IDs are just blank - has anyone else experienced this, or is this more likely to be a mistake on our side? Thanks!

**Comment by nebhale** [comment] 2018-02-14 18:17
@Aeolic Could simply be an escaping problem.  Any chance you can send over the command line (as reported by the CLI) that is run when you're successfully sending data?

**Comment by Aeolic** [comment] 2018-02-15 14:53
@nebhale I might misunderstand what you mean, but the command line never shows anything about jacoco sending data (I trigger a dump by using a custom TCP server and send a "dump" command to the jacoco client) - another question: Is it possible to supply port and address without using UPSs ? We have quite a lot of microservices running and right now I have to create a config for each service, because I want to use a different port for each service - Thanks!

**Comment by nebhale** [comment] 2018-02-15 20:29
@Aeolic When the buildpack notices a `jacoco` service, it [adds the appropriate `-javaagent` to the command line](https://github.com/cloudfoundry/java-buildpack/blob/1a22acf60d00dd0a0b72b032e659ff84771e8f83/spec/java_buildpack/framework/jacoco_agent_spec.rb#L65-L67):

```
-javaagent:$PWD/.java-buildpack/jacoco_agent/jacocoagent.jar=address=test-address,output=tcpclient,sessionid=$CF_INSTANCE_ID,excludes=test-excludes,includes=test-includes,port=6300
```

This is how the agent knows _where_ to send data.  I suspect that the problem is that the `$CF_INSTANCE_ID` is being evaluated too early and needs to be escaped, but I'm looking for some confirmation of that since I'm doing this a bit blind.

In 12 Factor applications, (CF is fundamentally a system for running 12 Factor applications) connections to external system are provided by the environment.  In CF, the manifestation of this idea is the concept of services.  So whether it's a database, an APM, or even a code coverage sink, all information of where to connect to and the credentials for connecting with are communicated via services.  From the perspective of the buildpack we don't care if a service is a user-provided service or a service-broker (i.e. "managed") service, so we always start with instructions on how to use a User Provided Service to communicate this.  If you find that it's very useful, you should *absolutely* write a Service Broker that knows how to spin up instances of the JaCoCo servers when `cf create-service` is called and provide that information to applications when `cf bind-service` is called.

**Comment by Aeolic** [comment] 2018-02-16 09:56
@nebhale now I understand what you were talking about, the part "when you're successfully sending data" got me a bit confused :)

`JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.12.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR 
-javaagent:$PWD/.java-buildpack/jacoco_agent/jacocoagent.jar=address=someIP,output=tcpclient,sessionid=$CF_INSTANCE_ID,port=somePort -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.10.0_RELEASE -totMemory=$MEMORY_LIMIT -stackThreads=250 -loadedClasses=14041 -poolType=metaspace -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher`

This is the command line we are using to launch the apps.

And thanks for the other answer as well!

**Comment by nebhale** [comment] 2018-02-16 16:19
OK, the problem is that the variable is called `$CF_INSTANCE_GUID` not `$CF_INSTANCE_ID`.  Updated now, so @Aeolic please have another go and let me know if you're getting a proper `sessionid`.

**Comment by jonathanamartin** [comment] 2018-02-20 14:29
This is somewhat unconventional.  However, @nebhale if you're good with the testing @Aeolic has completed I am too :).

**Comment by nebhale** [comment] 2018-02-20 14:31
I'm heading off to a conference for the rest of the week and would really like to get this merged this morning for a release, so I'm going to call this confirmed.  We can always change it if there's something wrong, but I think this is sufficient for a first try.

**Closed** 2018-02-20 14:32 UTC
Labels: framework

**Comment by jonathanamartin** [comment] 2018-02-20 14:39
Thanks!

**Comment by tdrury** [comment] 2018-03-22 14:41
I have a question about getting the coverage data out of CF: um, how do you do it? I've always used tcpserver mode on my (non-cloud) servers and it's fairly easy.

Is it possible to configure jacoco for tcpserver mode or is only tcpclient allowed?

I've never used tcpclient mode. When does it send coverage information? Reading the docs on tcpclient, it's not clear.

**Comment by konstantinblaesi** [comment] 2019-05-14 07:52
https://github.com/cloudfoundry/java-buildpack/pull/715#issuecomment-492109959

**Comment by pank9** [comment] 2020-11-03 13:06
> I used this option and see Jacoco being downloaded
> -----> Downloading Jacoco Agent 0.8.0 from https://java-buildpack.cloudfoundry.org/jacoco/jacoco-0.8.0.jar (1.0s)
> Expanding Jacoco Agent to .java-buildpack/jacoco_agent (0.0s)
> 
> name: xun-javaexample
> requested state: started
> instances: 1/1
> usage: 928M x 1 instances
> routes: xun-javaexample-introspective-ovolo.run.aws-usw02-pr.ice.predix.io
> last uploaded: Mon 29 Jan 09:55:49 PST 2018
> stack: cflinuxfs2
> buildpack: [http://github.com/cloudfoundry/java-buildpack.git#529-jacoco](https://github.com/cloudfoundry/java-buildpack.git#529-jacoco)
> start command: JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.12.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR
> -javaagent:$PWD/.java-buildpack/jacoco_agent/jacocoagent.jar=address=127.0.0.1,output=tcpclient,sessionid=$CF_INSTANCE_ID,includes=*,port=1010
> -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security
> $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.10.0_RELEASE -totMemory=$MEMORY_LIMIT -stackThreads=250 -loadedClasses=13289
> -poolType=metaspace -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && SERVER_PORT=$PORT JAVA_OPTS=$JAVA_OPTS
> JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre exec $PWD/java-hello-world-cf-example/bin/java-hello-world-cf-example
> 
> So how can I grab the jacoco data on the fly?

Hi 

> Hi All,
> I have pushed an app to the cloud foundry with this "-b [http://github.com/cloudfoundry/java-buildpack.git#529-jacoco](https://github.com/cloudfoundry/java-buildpack.git#529-jacoco)" option and I can see my app successfully started, but I cannot see any logs related to jacoco, I am wondering is there any other configuration I need to do for the jacoco to generate the coverage report, for example specify JAVA_OPTS related to jacoco?

Hi Xunwu,
I am trying to deploy the application from my command line using below command in order to use jacoco agent support but it is not working. I am getting error "ERR Failed to clone git repository at https://github.com/cloudfoundry/java-buildpack.git"

**Command**
cf push coverage-repo1 -b https://github.com/cloudfoundry/java-buildpack.git#529-jacoco

I am deploying app on cloud foundry with jacoco agent support to generate test case report.
