### ISSUE TITLE
GemFire session replication is broken when service instance name contains the string 'session-replication'

### ISSUE THREAD

**Issue by jdeppe-pivotal** [cloudfoundry/java-buildpack#142] opened 2015-02-12 19:19 UTC
If I create a GemFire session replication instance named `gem-session-replication`, my bound app fails to deploy with the following error:
```
± lh+jd |master ✗| → cf restage petclinic
Restaging app petclinic in org dev-test / space myspace as admin...
-----> Downloaded app package (26M)
-----> Downloaded app buildpack cache (4.0K)
[Services]                       WARN  A service with a name label or tag matching (?-mix:session-replication) was found, but was missing one of the required credentials [["hostname", "host"], "port", "password"]
-----> Java Buildpack Version: aa68bd8 (offline) | git@github.com:cloudfoundry/java-buildpack#aa68bd8
-----> Downloading Open Jdk JRE 1.8.0_25 from https://download.run.pivotal.io/openjdk/lucid/x86_64/openjdk-1.8.0_25.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.1s)
-----> Downloading Spring Auto Reconfiguration 1.5.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.5.0_RELEASE.jar (found in cache)
       Modifying /WEB-INF/web.xml for Auto Reconfiguration
-----> Downloading Tomcat Instance 8.0.17 from https://download.run.pivotal.io/tomcat/tomcat-8.0.17.tar.gz (found in cache)
       Expanding Tomcat to .java-buildpack/tomcat (0.1s)
-----> Downloading Tomcat Lifecycle Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-lifecycle-support/tomcat-lifecycle-support-2.4.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Logging Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-logging-support/tomcat-logging-support-2.4.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Access Logging Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-access-logging-support/tomcat-access-logging-support-2.4.0_RELEASE.jar (found in cache)
[Services]                       WARN  A service with a name label or tag matching (?-mix:session-replication) was found, but was missing one of the required credentials [["hostname", "host"], "port", "password"]
-----> Downloading Gem Fire 8.0.0 from https://download.run.pivotal.io/gem-fire/gem-fire-8.0.0.jar (found in cache)
-----> Downloading Gem Fire Logging Api 1.5.8 from https://download.run.pivotal.io/slf4j-api/slf4j-api-1.5.8.jar (found in cache)
-----> Downloading Gem Fire Logging 1.5.8 from https://download.run.pivotal.io/slf4j-jdk14/slf4j-jdk14-1.5.8.jar (found in cache)
-----> Downloading Gem Fire Modules 8.0.0_1 from https://download.run.pivotal.io/gem-fire-modules/gem-fire-modules-8.0.0_1.jar (found in cache)
-----> Downloading Gem Fire Modules Tomcat7 8.0.0_1 from https://download.run.pivotal.io/gem-fire-modules-tomcat7/gem-fire-modules-tomcat7-8.0.0_1.jar (found in cache)
-----> Downloading Gem Fire Security 8.0.0 from https://download.run.pivotal.io/gem-fire-security/gem-fire-security-8.0.0.jar (found in cache)
[Services]                       WARN  A service with a name label or tag matching (?-mix:session-replication) was found, but was missing one of the required credentials [["hostname", "host"], "port", "password"]
-----> Uploading droplet (83M)

FAILED
Server error, status code: 400, error code: 170001, message: Staging error: cannot get instances since staging failed

TIP: use 'cf logs petclinic --recent' for more information
```

It appears that the buildpack thinks it should be doing Redis session replication as opposed to GemFire.

**Comment by cgfrost** [comment] 2015-02-13 10:12
Hi,

Change the name of your service to `gem-session_replication` and it should work. Notice the underscore instead of the dash. It's a small difference, there is possibly an argument for making it more explicit now that we have more than one form of automatic session replication.

**Comment by nebhale** [comment] 2015-02-13 10:49
@jdeppe-pivotal Actually, you're correct, we've implemented this incorrectly.  Currently we look for `session_replication` which is inconsistent with the other kinds of session replication that look for `session-replication`.  We've [opened in an issue](https://www.pivotaltracker.com/story/show/88312476) to make it consistent, which will solve your problem.

**Comment by loganlee** [comment] 2015-02-13 23:24
Hi,

If I am understanding the issue, you are trying to trigger off of pattern matching in the service instance name.  When we walked through the original intent, the expectation was that you would trigger off of the presence of the session_replication tag in the bind response.

Developers can name their Service Instances whatever they want so I recommend the buildpack ignore the service instance name field.

**Comment by loganlee** [comment] 2015-02-18 00:19
Any update on this issue?

**Comment by cgfrost** [comment] 2015-02-18 09:04
Hi Logan,

It's likely to be later this week until I get round to looking at this one.
I believe this isn't blocking you as the work around is to include
'session_replication' in our service name. Let me know if this isn't the
case.

Chris.

On Wed, Feb 18, 2015 at 12:19 AM, Logan Lee <notifications@github.com>
wrote:

> Any update on this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/java-buildpack/issues/142#issuecomment-74785222>
> .
>



-- 
--
Christopher Frost - GoPivotal UK

**Comment by cgfrost** [comment] 2015-02-20 12:30
@loganlee @jdeppe-pivotal Hi,

We've looked at this in more detail now and your application didn't fail to stage due to the Redis detection. We provide support for Redis session replication based on a label, tag or name containing the string ```session-replication```. So by putting that in the name of your service it matched on Redis and then issued a warning that it wasn't actually bound to a valid Redis service. This did not fail your application staging.

Notice that the application also successfully matched on Gem Fire, due to the Gem Fire service adding a ```session_replication``` tag to the service it created. You can see all the Gem Fire dependencies being downloaded. I believe your application has failed for another reason and you will need to look in the logs to see additional out put, ```cf logs petclinic --recent```. 

We have made a change to the code to reduce the ```WARN``` messages to ```DEBUG``` as this can be confusing but we still need to log something out to provide support for user provided services.

We would like to close this issue out as 'working as designed' but would like to get your agreement that you are happy with how this is implemented. That you can name your Gem Fire service with any name you like but if that name happens to contain ```session-replication``` it's going to trigger the Redis support in addition to the Gem Fire support as happened above.

**Comment by jdeppe-pivotal** [comment] 2015-02-20 19:30
Indeed, you're right. It looks like the 'failure to stage' message was as a result of something else wrong and not because of the name of the service instance.

**Comment by cgfrost** [comment] 2015-02-24 08:57
Thanks. We're going to run a release of the buildpack early next week so shout before then if you need anything changing in the GemFire support before then.

**Closed by cgfrost** 2015-02-24 08:58 UTC
