### ISSUE TITLE
app deployment failing with new new relic jar version 3.19.0: https://download.run.pivotal.io/new-relic/new-relic-3.19.0.jar

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry/java-buildpack#211] opened 2015-08-04 05:51 UTC
push app is failing with build pack version Java Buildpack Version: v3.x and new relic jar version jar version 3.19.0: https://download.run.pivotal.io/new-relic/new-relic-3.19.0.jar while binding to the new relic service broker

**Comment by cgfrost** [comment] 2015-08-04 13:57
Hi, 

We haven't been able to recreate this issue. Can you give us more information on how you are pushing you application. Any environment variables and the application manifest would be helpful along with the logs (`cf logs myapp --recent`). Finally, why are you using v2.7.1 of the buildpack? 

Thanks, Chris.

**Comment by amulyas** [comment] 2015-08-04 20:59
even with the latest buildpack version 3.0 we are having same problem..

**Comment by amulyas** [comment] 2015-08-04 21:02
2015-08-04T13:37:57.81-0700 [App/0]      OUT org.apache.openjpa.persistence.ArgumentException: Failed to execute query "select u from User u where u.username = :username and u.tenancy.uuid = :tenantUuid". Check the query syntax for correctness. See nested exception for details.
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:871)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:793)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.kernel.DelegatingQuery.execute(DelegatingQuery.java:541)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.persistence.QueryImpl.execute(QueryImpl.java:274)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.persistence.QueryImpl.getResultList(QueryImpl.java:290)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.aggregator.plugins.refdb.JpaReferenceResolver$EntityQueryBasedResolver.resolve(JpaReferenceResolver.java:203)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.aggregator.PrioritizingReferenceResolver.resolve(PrioritizingReferenceResolver.java:140)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.aggregator.DefaultAggregator$6.get(DefaultAggregator.java:987)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.aggregator.DefaultAggregator.aggregate(DefaultAggregator.java:289)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.aggregator.DefaultAggregator.aggregate(DefaultAggregator.java:984)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.usermanagement.service.impl.UserProfileSupplier.get(UserProfileSupplier.java:167)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.usermanagement.service.impl.UserProfileSupplier.get(UserProfileSupplier.java:45)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.usermanagement.service.impl.UserProfileService.getUserProfile(UserProfileService.java:46)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.security.context.DefaultSecurityContext.fetchUserProfile(DefaultSecurityContext.java:367)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.security.context.DefaultSecurityContext.access$300(DefaultSecurityContext.java:22)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.security.context.DefaultSecurityContext$1.call(DefaultSecurityContext.java:319)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.security.context.DefaultSecurityContext$1.call(DefaultSecurityContext.java:316)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4724)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4721)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.security.context.DefaultSecurityContext.getUserProfile(DefaultSecurityContext.java:316)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.security.context.DefaultSecurityContext.getExcludedFields(DefaultSecurityContext.java:73)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.ge.apm.usermanagement.rest.impl.UsersResource.getUsers(UsersResource.java:224)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at java.lang.reflect.Method.invoke(Method.java:497)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:271)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)

**Comment by nebhale** [comment] 2015-08-04 21:04
@amulyas Unfortunately, those logs are a bit too late for us to see what New Relic is doing.  However, `org.apache.openjpa.persistence.ArgumentException: Failed to execute query "select u from User u where u.username = :username and u.tenancy.uuid = :tenantUuid". Check the query syntax for correctness. See nested exception for details.` appears to point to OpenJPA rather than New Relic.  Does unbinding from the New Relic service allow your application to start successfully?

**Comment by cthinkel** [comment] 2015-08-04 21:30
@nebhale Here's the important bit which led us to believe it's a newrelic issue. Buried deep inside the stacktrace:


2015-08-04T13:37:57.81-0700 [App/0]      OUT Caused by: java.lang.NullPointerException: null
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.lib.jdbc.DelegatingResultSet.hashCode(DelegatingResultSet.java:86)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at java.util.WeakHashMap.hash(WeakHashMap.java:298)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at java.util.WeakHashMap.get(WeakHashMap.java:396)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at java.util.Collections$SynchronizedMap.get(Collections.java:2584)
**2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.newrelic.weave.InstanceMap.get(InstanceMap.java:42)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at com.newrelic.weave.java.sql.ResultSet_1052372728_nr_ext.<init>(Unknown Source)**
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.lib.jdbc.DelegatingResultSet.<init>(DelegatingResultSet.java:59)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.lib.jdbc.DelegatingPreparedStatement.wrapResult(DelegatingPreparedStatement.java:77)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.lib.jdbc.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:271)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.kernel.JDBCStoreManager$CancelPreparedStatement.executeQuery(JDBCStoreManager.java:1800)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.lib.jdbc.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:258)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.sql.SelectImpl.executeQuery(SelectImpl.java:500)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.sql.SelectImpl.execute(SelectImpl.java:425)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.sql.SelectImpl.execute(SelectImpl.java:392)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.sql.LogicalUnion$UnionSelect.execute(LogicalUnion.java:427)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.sql.LogicalUnion.execute(LogicalUnion.java:230)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.sql.LogicalUnion.execute(LogicalUnion.java:220)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.jdbc.kernel.SelectResultObjectProvider.open(SelectResultObjectProvider.java:93)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.kernel.QueryImpl$PackingResultObjectProvider.open(QueryImpl.java:2068)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.lib.rop.EagerResultList.<init>(EagerResultList.java:33)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.kernel.QueryImpl.toResult(QueryImpl.java:1250)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:1006)
2015-08-04T13:37:57.81-0700 [App/0]      OUT at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:862)
2015-08-04T13:37:57.81-0700 [App/0]      OUT ... 119 common frames omitted


FYI - we're using OpenJPA version 2.4.0

**Comment by nebhale** [comment] 2015-08-04 21:36
Have you opened an issue with the New Relic team?  I don't think we're likely to roll back to an earlier version of New Relic for everyone based on this issue (at least not until we hear about it a lot more, or New Relic requests that we do so), but you may want to roll back for your application specifically.  You can do this with the following command:

```
$ cf set-env <APP_NAME> JBP_CONFIG_NEW_RELIC_AGENT 'version: 3.18.0'
```

**Comment by amulyas** [comment] 2015-08-04 21:37
@nebhale this is a smart way of doing this .. we did the same but by customizing the build pack thanks for the input

**Comment by cthinkel** [comment] 2015-08-04 22:01
@nebhale Thanks for the suggestion to roll back the app. 

We'll open a case with the New Relic team to see what they have to say.

**Comment by cgfrost** [comment] 2015-08-05 17:25
Is rolling back the application a good enough work around for you? If so can we close this issue off. If you find the problem is actually our fault, can provide more information you can re-open and we will of course look in to it again.

**Comment by cthinkel** [comment] 2015-08-05 17:29
Yes, we have a couple of workarounds so we're unblocked now. All signs point to this being a bug in the latest 3.19 release of the newrelic java agent, so we'll take it up with them. We'll revisit this thread if any action's required from your side. Thanks!

**Comment by cgfrost** [comment] 2015-08-05 17:40
That's great, I hope New Relic are able to help you and thanks for the quick response.

**Closed by cgfrost** 2015-08-05 17:40 UTC

**Comment by amulyas** [comment] 2015-08-05 18:33
I think the env variable thing not working as expected .. I can see env variable but still its downloading latest 3.19 version 


JBP_CONFIG_NEW_RELIC_AGENT: version: 3.18.0

sfo1502393292a:~ 502393292$ cf logs app --recent
Connected, dumping recent logs for app apm-note-management-acceptance in org org / space space as admin...

2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:111)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at com.sun.proxy.$Proxy133.findNotesByParentUuid(Unknown Source)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-08-05T10:10:30.47-0700 [App/0]      OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by nebhale** [comment] 2015-08-05 18:34
Did you `restage` (as opposed to `restart`) the application?  Can you also provide the staging output?
